## 浏览器报告的错误

## 错误处理

### try-catch

```
try{
    // 可能会出错的代码
} catch(error){
    // 处理
    console.error(error)
} finally {
    // 都会执行
}
```

#### 错误类型

- Error
- EvalError: eval报错 eg: new eval();
- RangeError: 数值超出范围 eg: var items1 = new Array(-20);
- ReferenceError: 访问不存在的变量
- SyntaxError: 在eval中使用错误语法 eg: eval("a ++ b")
- TypeError: 类型错误 eg: var o = new 10;
- URIError: encodeURI传入格式不正确

### 抛出错误

```
throw 12345;
// 模拟浏览器错误
throw new SyntaxError("I don’t like your syntax.");
throw new TypeError("What type of variable do you take me for?"); throw new RangeError("Sorry, you just don’t have the range.");
throw new EvalError("That doesn’t evaluate.");
throw new URIError("Uri, is that you?");
throw new ReferenceError("You didn’t cite your references properly.");
```

### 错误事件

没有通过try-catch处理的错误都会触发window.error

```
window.onerror = function(message, url, line){
        alert(message);
};
```

